// Full landing-page copy for all 6 supported languages. Kept separate from
// Landing.jsx so the component stays about layout/structure, not text.
import { MessageCircle, Brain, CalendarClock, HeartHandshake, ShieldCheck, MessagesSquare, BookMarked, Repeat } from "lucide-react";

const FEATURE_META = [
  { icon: MessageCircle, color: "text-sky-400 bg-sky-500/10" },
  { icon: Brain, color: "text-fuchsia-400 bg-fuchsia-500/10" },
  { icon: CalendarClock, color: "text-indigo-400 bg-indigo-500/10" },
  { icon: HeartHandshake, color: "text-pink-400 bg-pink-500/10" },
  { icon: ShieldCheck, color: "text-emerald-400 bg-emerald-500/10" },
];
const HOW_META = [{ icon: MessagesSquare }, { icon: BookMarked }, { icon: Repeat }];

function withMeta(items, meta) {
  return items.map((it, i) => ({ ...it, ...meta[i] }));
}

const RAW = {
  tr: {
    nav: ["Ana Sayfa", "Özellikler", "Nasıl Çalışır", "Luna Hakkında", "Güvenlik", "SSS", "İletişim"],
    ctaStart: "Hemen Başla",
    badge: "YAPAY ZEKA ARKADAŞIN",
    heroTitle: ["Sadece cevap veren", "bir yapay zeka değil."],
    heroLead: "seni tanıyan, hatırlayan ve zamanla seninle birlikte gelişen kişisel bir yapay zeka arkadaşı.",
    heroSub: "Konuştukça öğrenir, önemli anları hatırlar ve ihtiyacına göre sıcak bir arkadaş ya da net bir asistan olur.",
    ctaMeet: "Luna ile Tanış",
    ctaExplore: "Özellikleri Keşfet",
    onlineBadge: "Luna Online",
    onlineMsg: "Merhaba! Bugün nasıl yardımcı olabilirim? 🌙",
    featuresTitle: "Luna ile neler yapabilirsin?",
    featuresSub: "Her biri, sıradan bir asistanın ötesine geçen beş temel yetenek.",
    features: [
      { title: "Doğal Sohbet", desc: "Yapay bir asistan gibi değil, gerçek bir arkadaşınla konuşuyormuş gibi doğal, akıcı ve bağlam kaybetmeyen sohbetler kurar." },
      { title: "Akıllı Hatırlama", desc: "Ona anlattığın önemli detayları, tercihlerini ve önemli tarihleri aklında tutar; sen tekrar hatırlatmak zorunda kalmazsın." },
      { title: "Planlama", desc: "Hedeflerini, notlarını ve hatırlatmalarını takip eder; günlük düzenini kurman için sana yardımcı olur." },
      { title: "Destek & Motivasyon", desc: "Zor bir gün geçirdiğinde ya da motivasyona ihtiyaç duyduğunda, seni gerçekten tanıyan biri gibi yanında olur." },
      { title: "Güvenli & Özel", desc: "Hafızan ve sohbetlerin yalnızca sana ait; cihazına özel bir kimlikle korunur, üçüncü taraflarla asla paylaşılmaz." },
    ],
    howTitle: "Luna Nasıl Çalışır?",
    howSub: "Üç basit adımda, seni gerçekten tanıyan bir yapay zeka arkadaşı.",
    how: [
      { title: "Konuş", desc: "Yazarak ya da sesli olarak Luna ile sohbete başla — Arkadaş Modu'nda sıcak bir dost bulursun, LunaWorks Modu'nda ise belge, görsel ve daha fazlasını üretirsin." },
      { title: "Hatırlar", desc: "Konuştukça Luna önemli detayları, tercihlerini ve olayları hafızasına kaydeder — sen aynı şeyi tekrar anlatmak zorunda kalmazsın." },
      { title: "Zamanla Seninle Gelişir", desc: "Hafızası büyüdükçe seni daha iyi tanır; verdiği cevaplar ve önerdiği destek, senin ihtiyaçlarına daha yakın hale gelir." },
    ],
    aboutTitle: "Luna Hakkında",
    aboutP1: ["Luna, XSF Technology tarafından geliştirilen kişisel bir yapay zeka arkadaşıdır. Bir asistan değil, seni tanıyan, hatırlayan ve zamanla seninle birlikte gelişen bir arkadaş olmayı hedefler. İki farklı modda kullanabilirsin: sıcak ve samimi ", "Arkadaş Modu", ", ya da belge, görsel ve daha fazlasını ürettiren ", "LunaWorks Modu", "."],
    aboutP2: "Çoğu yapay zeka aracı her konuşmaya sıfırdan başlar. Luna farklı çalışır: sana özel bir hafıza sistemiyle önemli anları, tercihlerini ve hedeflerini zaman içinde biriktirir — böylece aradan günler geçse bile kaldığın yerden, seni hatırlayarak devam eder.",
    stats: [{ value: "7/24", label: "Yanında" }, { value: "6 Dil", label: "Desteklenen" }, { value: "%100", label: "Güvenli" }, { value: "2", label: "Kişilik Modu" }],
    securityTitle: "Güvenlik & Gizlilik",
    security: [
      "Konuşmaların ve hafızan yalnızca sana ait, kimlik bilgin cihazına özel bir anahtarla korunur.",
      "Telefon ve web arasında hafızanı taşımak için tek kullanımlık, süresi dolan eşleştirme kodları kullanılır.",
      "İstediğin zaman hafızanı veya sohbet geçmişini tamamen silebilirsin.",
      "Verilerin üçüncü taraflarla paylaşılmaz ya da satılmaz.",
    ],
    faqTitle: "Sıkça Sorulan Sorular",
    faq: [
      { q: "Luna verilerimi nasıl saklıyor?", a: "Sohbetlerin ve hafızan, cihazına özel bir kimlik anahtarıyla ilişkilendirilir. Verilerin üçüncü taraflarla paylaşılmaz ya da satılmaz; istediğin an tamamen silebilirsin." },
      { q: "Luna'yı hem telefonda hem bilgisayarda kullanabilir miyim?", a: "Evet. Mobil uygulamada oluşturduğun eşleştirme koduyla web tarayıcını aynı hesaba bağlayabilir, hafızanı iki cihaz arasında senkron tutabilirsin." },
      { q: "Arkadaş Modu ile LunaWorks Modu arasındaki fark nedir?", a: "Arkadaş Modu sıcak, samimi ve destekleyici bir sohbet deneyimi sunar. LunaWorks Modu ise aynı sohbetten PDF, Word, Excel, PowerPoint, tablo, grafik ve görsel üretmeni sağlar. İkisi arasında istediğin zaman geçiş yapabilirsin." },
      { q: "Luna'yı kullanmak ücretli mi?", a: "Luna'yı ücretsiz kullanmaya başlayabilirsin. Daha yüksek kullanım limiti ve gelişmiş özellikler isteyenler için Luna Premium ve Premium Plus paketleri mevcuttur." },
      { q: "Luna hangi dilleri destekliyor?", a: "Luna; Türkçe, İngilizce, İspanyolca, Almanca, Rusça ve İtalyanca dillerinde doğal biçimde konuşabilir. Ayarlar'dan dilini seçmen yeterli." },
    ],
    readyTitle: "Hazır mısın?",
    readySub: "Luna'yla tanışmak sadece bir tık uzağında.",
    footerRights: "Tüm hakları saklıdır.",
  },
  en: {
    nav: ["Home", "Features", "How It Works", "About Luna", "Security", "FAQ", "Contact"],
    ctaStart: "Get Started",
    badge: "YOUR AI COMPANION",
    heroTitle: ["Not just an AI", "that answers questions."],
    heroLead: "a personal AI companion that knows you, remembers you, and grows alongside you over time.",
    heroSub: "The more you talk, the more she learns — remembering what matters and becoming a warm friend or a sharp assistant, whichever you need.",
    ctaMeet: "Meet Luna",
    ctaExplore: "Explore Features",
    onlineBadge: "Luna Online",
    onlineMsg: "Hi! How can I help you today? 🌙",
    featuresTitle: "What can you do with Luna?",
    featuresSub: "Five core abilities, each going beyond an ordinary assistant.",
    features: [
      { title: "Natural Conversation", desc: "Talks with you like a real friend, not a robotic assistant — fluid, natural, and never losing context." },
      { title: "Smart Memory", desc: "Remembers the important details, preferences, and dates you've shared, so you never have to repeat yourself." },
      { title: "Planning", desc: "Tracks your goals, notes, and reminders — helping you build and keep a daily routine." },
      { title: "Support & Motivation", desc: "On a hard day, or whenever you need a boost, Luna shows up like someone who truly knows you." },
      { title: "Private & Secure", desc: "Your memory and conversations belong only to you — protected by a device-specific identity, never shared with third parties." },
    ],
    howTitle: "How Luna Works",
    howSub: "Three simple steps to an AI companion that truly knows you.",
    how: [
      { title: "Talk", desc: "Start chatting with Luna by text or voice — a warm friend in Friend Mode, or a document/image generator in LunaWorks Mode." },
      { title: "She Remembers", desc: "As you talk, Luna saves the important details, preferences, and events to memory — so you never repeat yourself." },
      { title: "She Grows With You", desc: "As her memory grows, she understands you better — her answers and support become more tailored to your needs over time." },
    ],
    aboutTitle: "About Luna",
    aboutP1: ["Luna is a personal AI companion built by XSF Technology. Not an assistant — she aims to be a friend who knows you, remembers you, and grows alongside you over time. You can use her in two modes: warm and personal ", "Friend Mode", ", or document/image-generating ", "LunaWorks Mode", "."],
    aboutP2: "Most AI tools start every conversation from scratch. Luna works differently: with a memory system built just for you, she accumulates important moments, preferences, and goals over time — so even after days apart, she picks up right where you left off, remembering you.",
    stats: [{ value: "24/7", label: "Always On" }, { value: "6 Langs", label: "Supported" }, { value: "100%", label: "Private" }, { value: "2", label: "Personas" }],
    securityTitle: "Security & Privacy",
    security: [
      "Your conversations and memory belong only to you, protected by a device-specific identity key.",
      "Moving your memory between phone and web uses one-time, expiring pairing codes.",
      "You can fully delete your memory or chat history at any time.",
      "Your data is never shared or sold to third parties.",
    ],
    faqTitle: "Frequently Asked Questions",
    faq: [
      { q: "How does Luna store my data?", a: "Your chats and memory are tied to a device-specific identity key. Your data is never shared or sold to third parties, and you can delete it completely at any time." },
      { q: "Can I use Luna on both phone and computer?", a: "Yes. Using the pairing code generated in the mobile app, you can link your web browser to the same account and keep your memory in sync across both devices." },
      { q: "What's the difference between Friend Mode and LunaWorks Mode?", a: "Friend Mode offers a warm, personal, supportive conversation experience. LunaWorks Mode lets you generate PDFs, Word docs, Excel sheets, PowerPoint slides, tables, charts, and images from that same conversation. You can switch between them anytime." },
      { q: "Is Luna free to use?", a: "You can start using Luna for free. For a higher usage limit and advanced features, Luna Premium and Premium Plus plans are available." },
      { q: "What languages does Luna support?", a: "Luna can speak naturally in Turkish, English, Spanish, German, Russian, and Italian. Just pick your language in Settings." },
    ],
    readyTitle: "Ready?",
    readySub: "Meeting Luna is just one click away.",
    footerRights: "All rights reserved.",
  },
  es: {
    nav: ["Inicio", "Características", "Cómo Funciona", "Sobre Luna", "Seguridad", "Preguntas", "Contacto"],
    ctaStart: "Empezar Ahora",
    badge: "TU COMPAÑERA DE IA",
    heroTitle: ["No es solo una IA", "que responde preguntas."],
    heroLead: "una compañera de IA personal que te conoce, te recuerda y evoluciona contigo con el tiempo.",
    heroSub: "Cuanto más hablas, más aprende — recuerda lo importante y se convierte en una amiga cercana o en una asistente precisa, según lo que necesites.",
    ctaMeet: "Conoce a Luna",
    ctaExplore: "Explorar Funciones",
    onlineBadge: "Luna En Línea",
    onlineMsg: "¡Hola! ¿Cómo puedo ayudarte hoy? 🌙",
    featuresTitle: "¿Qué puedes hacer con Luna?",
    featuresSub: "Cinco capacidades esenciales, cada una más allá de una asistente común.",
    features: [
      { title: "Conversación Natural", desc: "Habla contigo como una amiga real, no como una asistente robótica — fluida, natural y sin perder nunca el contexto." },
      { title: "Memoria Inteligente", desc: "Recuerda los detalles importantes, preferencias y fechas que le has contado, para que nunca tengas que repetirte." },
      { title: "Planificación", desc: "Hace seguimiento de tus metas, notas y recordatorios — ayudándote a construir y mantener una rutina diaria." },
      { title: "Apoyo y Motivación", desc: "En un día difícil, o cuando necesitas un impulso, Luna está presente como alguien que realmente te conoce." },
      { title: "Privada y Segura", desc: "Tu memoria y conversaciones te pertenecen solo a ti — protegidas por una identidad específica de tu dispositivo, nunca compartida con terceros." },
    ],
    howTitle: "¿Cómo Funciona Luna?",
    howSub: "Tres simples pasos hacia una compañera de IA que realmente te conoce.",
    how: [
      { title: "Habla", desc: "Empieza a chatear con Luna por texto o voz — una amiga cercana en Modo Amigo, o una generadora de documentos e imágenes en Modo LunaWorks." },
      { title: "Ella Recuerda", desc: "Mientras hablas, Luna guarda los detalles importantes, preferencias y eventos en su memoria — así nunca tienes que repetirte." },
      { title: "Evoluciona Contigo", desc: "A medida que su memoria crece, te entiende mejor — sus respuestas y apoyo se ajustan cada vez más a tus necesidades." },
    ],
    aboutTitle: "Sobre Luna",
    aboutP1: ["Luna es una compañera de IA personal creada por XSF Technology. No es una asistente — su objetivo es ser una amiga que te conoce, te recuerda y evoluciona contigo con el tiempo. Puedes usarla en dos modos: cálido y cercano ", "Modo Amigo", ", o generador de documentos e imágenes ", "Modo LunaWorks", "."],
    aboutP2: "La mayoría de las herramientas de IA empiezan cada conversación desde cero. Luna funciona diferente: con un sistema de memoria creado solo para ti, acumula momentos importantes, preferencias y metas con el tiempo — así, incluso después de días sin hablar, continúa justo donde lo dejaste, recordándote.",
    stats: [{ value: "24/7", label: "Disponible" }, { value: "6 Idiomas", label: "Soportados" }, { value: "100%", label: "Privada" }, { value: "2", label: "Personalidades" }],
    securityTitle: "Seguridad y Privacidad",
    security: [
      "Tus conversaciones y memoria te pertenecen solo a ti, protegidas por una clave de identidad específica del dispositivo.",
      "Para mover tu memoria entre el teléfono y la web se usan códigos de emparejamiento de un solo uso y con caducidad.",
      "Puedes eliminar por completo tu memoria o historial de chat en cualquier momento.",
      "Tus datos nunca se comparten ni se venden a terceros.",
    ],
    faqTitle: "Preguntas Frecuentes",
    faq: [
      { q: "¿Cómo almacena Luna mis datos?", a: "Tus chats y memoria están vinculados a una clave de identidad específica del dispositivo. Tus datos nunca se comparten ni se venden a terceros, y puedes eliminarlos por completo en cualquier momento." },
      { q: "¿Puedo usar Luna tanto en el teléfono como en la computadora?", a: "Sí. Usando el código de emparejamiento generado en la app móvil, puedes vincular tu navegador web a la misma cuenta y mantener tu memoria sincronizada entre ambos dispositivos." },
      { q: "¿Cuál es la diferencia entre el Modo Amigo y el Modo LunaWorks?", a: "El Modo Amigo ofrece una experiencia de conversación cálida, cercana y de apoyo. El Modo LunaWorks te permite generar PDFs, documentos Word, hojas Excel, presentaciones PowerPoint, tablas, gráficos e imágenes desde esa misma conversación. Puedes cambiar entre ambos cuando quieras." },
      { q: "¿Es gratis usar Luna?", a: "Puedes empezar a usar Luna gratis. Para un límite de uso más alto y funciones avanzadas, están disponibles los planes Luna Premium y Premium Plus." },
      { q: "¿Qué idiomas soporta Luna?", a: "Luna puede hablar naturalmente en turco, inglés, español, alemán, ruso e italiano. Solo elige tu idioma en Ajustes." },
    ],
    readyTitle: "¿Listo?",
    readySub: "Conocer a Luna está a solo un clic de distancia.",
    footerRights: "Todos los derechos reservados.",
  },
  de: {
    nav: ["Start", "Funktionen", "So Funktioniert's", "Über Luna", "Sicherheit", "FAQ", "Kontakt"],
    ctaStart: "Jetzt Starten",
    badge: "DEINE KI-BEGLEITERIN",
    heroTitle: ["Nicht nur eine KI,", "die Fragen beantwortet."],
    heroLead: "eine persönliche KI-Begleiterin, die dich kennt, sich erinnert und mit der Zeit mit dir wächst.",
    heroSub: "Je mehr ihr sprecht, desto mehr lernt sie — sie merkt sich das Wichtige und wird je nach Bedarf zur warmherzigen Freundin oder zur präzisen Assistentin.",
    ctaMeet: "Luna Kennenlernen",
    ctaExplore: "Funktionen Entdecken",
    onlineBadge: "Luna Online",
    onlineMsg: "Hallo! Wie kann ich dir heute helfen? 🌙",
    featuresTitle: "Was kannst du mit Luna machen?",
    featuresSub: "Fünf Kernfähigkeiten, jede weit über eine gewöhnliche Assistentin hinaus.",
    features: [
      { title: "Natürliche Gespräche", desc: "Spricht mit dir wie eine echte Freundin, nicht wie eine roboterhafte Assistentin — flüssig, natürlich und ohne je den Kontext zu verlieren." },
      { title: "Intelligentes Gedächtnis", desc: "Merkt sich wichtige Details, Vorlieben und Termine, die du ihr erzählt hast — du musst dich nie wiederholen." },
      { title: "Planung", desc: "Behält deine Ziele, Notizen und Erinnerungen im Blick — und hilft dir, eine tägliche Routine aufzubauen." },
      { title: "Unterstützung & Motivation", desc: "An einem schweren Tag oder wenn du einen Motivationsschub brauchst, ist Luna da wie jemand, der dich wirklich kennt." },
      { title: "Privat & Sicher", desc: "Dein Gedächtnis und deine Gespräche gehören nur dir — geschützt durch eine geräte­spezifische Identität, nie mit Dritten geteilt." },
    ],
    howTitle: "Wie Luna Funktioniert",
    howSub: "Drei einfache Schritte zu einer KI-Begleiterin, die dich wirklich kennt.",
    how: [
      { title: "Sprich", desc: "Beginne per Text oder Sprache mit Luna zu chatten — eine warmherzige Freundin im Freundes-Modus, oder eine Dokument- und Bildgeneratorin im LunaWorks-Modus." },
      { title: "Sie Erinnert Sich", desc: "Während ihr sprecht, speichert Luna wichtige Details, Vorlieben und Ereignisse in ihrem Gedächtnis — du musst dich nie wiederholen." },
      { title: "Sie Wächst Mit Dir", desc: "Mit wachsendem Gedächtnis versteht sie dich besser — ihre Antworten und Unterstützung werden mit der Zeit passgenauer." },
    ],
    aboutTitle: "Über Luna",
    aboutP1: ["Luna ist eine persönliche KI-Begleiterin, entwickelt von XSF Technology. Keine Assistentin — sie will eine Freundin sein, die dich kennt, sich erinnert und mit der Zeit mit dir wächst. Du kannst sie in zwei Modi nutzen: warmherzig und persönlich im ", "Freundes-Modus", ", oder Dokumente und Bilder erzeugend im ", "LunaWorks-Modus", "."],
    aboutP2: "Die meisten KI-Tools beginnen jedes Gespräch bei null. Luna arbeitet anders: mit einem Gedächtnissystem nur für dich sammelt sie mit der Zeit wichtige Momente, Vorlieben und Ziele — so knüpft sie selbst nach Tagen genau dort an, wo ihr aufgehört habt, und erinnert sich an dich.",
    stats: [{ value: "24/7", label: "Immer Da" }, { value: "6 Sprachen", label: "Unterstützt" }, { value: "100%", label: "Privat" }, { value: "2", label: "Persönlichkeiten" }],
    securityTitle: "Sicherheit & Datenschutz",
    security: [
      "Deine Gespräche und dein Gedächtnis gehören nur dir, geschützt durch einen geräte­spezifischen Identitätsschlüssel.",
      "Um dein Gedächtnis zwischen Handy und Web zu übertragen, werden einmalige, ablaufende Kopplungscodes verwendet.",
      "Du kannst dein Gedächtnis oder deinen Chatverlauf jederzeit vollständig löschen.",
      "Deine Daten werden niemals an Dritte weitergegeben oder verkauft.",
    ],
    faqTitle: "Häufig Gestellte Fragen",
    faq: [
      { q: "Wie speichert Luna meine Daten?", a: "Deine Chats und dein Gedächtnis sind an einen geräte­spezifischen Identitätsschlüssel gebunden. Deine Daten werden niemals an Dritte weitergegeben oder verkauft, und du kannst sie jederzeit vollständig löschen." },
      { q: "Kann ich Luna sowohl auf dem Handy als auch am Computer nutzen?", a: "Ja. Mit dem in der mobilen App erzeugten Kopplungscode kannst du deinen Webbrowser mit demselben Konto verbinden und dein Gedächtnis auf beiden Geräten synchron halten." },
      { q: "Was ist der Unterschied zwischen Freundes-Modus und LunaWorks-Modus?", a: "Der Freundes-Modus bietet ein warmherziges, persönliches, unterstützendes Gesprächserlebnis. Der LunaWorks-Modus lässt dich aus demselben Gespräch heraus PDFs, Word-Dokumente, Excel-Tabellen, PowerPoint-Folien, Tabellen, Diagramme und Bilder erzeugen. Du kannst jederzeit zwischen beiden wechseln." },
      { q: "Ist Luna kostenlos nutzbar?", a: "Du kannst Luna kostenlos nutzen. Für ein höheres Nutzungslimit und erweiterte Funktionen stehen die Pläne Luna Premium und Premium Plus zur Verfügung." },
      { q: "Welche Sprachen unterstützt Luna?", a: "Luna kann natürlich auf Türkisch, Englisch, Spanisch, Deutsch, Russisch und Italienisch sprechen. Wähle einfach deine Sprache in den Einstellungen." },
    ],
    readyTitle: "Bereit?",
    readySub: "Luna kennenzulernen ist nur einen Klick entfernt.",
    footerRights: "Alle Rechte vorbehalten.",
  },
  ru: {
    nav: ["Главная", "Возможности", "Как Это Работает", "О Luna", "Безопасность", "Вопросы", "Контакты"],
    ctaStart: "Начать",
    badge: "ТВОЙ ИИ-ДРУГ",
    heroTitle: ["Не просто ИИ,", "который отвечает на вопросы."],
    heroLead: "личный ИИ-компаньон, который знает тебя, помнит тебя и развивается вместе с тобой.",
    heroSub: "Чем больше вы общаетесь, тем больше она узнаёт — запоминает важное и становится то тёплым другом, то чётким помощником, в зависимости от того, что тебе нужно.",
    ctaMeet: "Познакомиться с Luna",
    ctaExplore: "Изучить Возможности",
    onlineBadge: "Luna Онлайн",
    onlineMsg: "Привет! Чем могу помочь сегодня? 🌙",
    featuresTitle: "Что ты можешь делать с Luna?",
    featuresSub: "Пять основных способностей, каждая выходит за рамки обычного помощника.",
    features: [
      { title: "Естественное Общение", desc: "Разговаривает с тобой как настоящий друг, а не как роботизированный помощник — плавно, естественно и никогда не теряя контекст." },
      { title: "Умная Память", desc: "Запоминает важные детали, предпочтения и даты, о которых ты рассказал — тебе никогда не придётся повторяться." },
      { title: "Планирование", desc: "Отслеживает твои цели, заметки и напоминания — помогая выстроить и поддерживать ежедневный распорядок." },
      { title: "Поддержка и Мотивация", desc: "В трудный день или когда нужен заряд мотивации, Luna рядом, как тот, кто действительно тебя знает." },
      { title: "Приватность и Безопасность", desc: "Твоя память и переписка принадлежат только тебе — защищены уникальным идентификатором устройства и никогда не передаются третьим лицам." },
    ],
    howTitle: "Как Работает Luna",
    howSub: "Три простых шага к ИИ-другу, который действительно тебя знает.",
    how: [
      { title: "Говори", desc: "Начни общение с Luna текстом или голосом — тёплый друг в Режиме Друга или генератор документов и изображений в Режиме LunaWorks." },
      { title: "Она Запоминает", desc: "Пока вы общаетесь, Luna сохраняет важные детали, предпочтения и события в памяти — тебе не нужно повторяться." },
      { title: "Растёт Вместе с Тобой", desc: "По мере роста памяти она понимает тебя лучше — её ответы и поддержка со временем становятся точнее под твои нужды." },
    ],
    aboutTitle: "О Luna",
    aboutP1: ["Luna — личный ИИ-компаньон, созданный компанией XSF Technology. Не помощник — она стремится быть другом, который знает тебя, помнит тебя и развивается вместе с тобой. Её можно использовать в двух режимах: тёплый и личный ", "Режим Друга", ", или создающий документы и изображения ", "Режим LunaWorks", "."],
    aboutP2: "Большинство ИИ-инструментов начинают каждый разговор с нуля. Luna работает иначе: благодаря системе памяти, созданной именно для тебя, она со временем накапливает важные моменты, предпочтения и цели — поэтому даже спустя дни она продолжает с того места, на котором вы остановились, помня тебя.",
    stats: [{ value: "24/7", label: "Всегда Рядом" }, { value: "6 Языков", label: "Поддерживается" }, { value: "100%", label: "Приватно" }, { value: "2", label: "Личности" }],
    securityTitle: "Безопасность и Приватность",
    security: [
      "Твои переписки и память принадлежат только тебе, защищены уникальным ключом устройства.",
      "Для переноса памяти между телефоном и веб-версией используются одноразовые коды сопряжения с истекающим сроком.",
      "Ты можешь полностью удалить свою память или историю чата в любой момент.",
      "Твои данные никогда не передаются и не продаются третьим лицам.",
    ],
    faqTitle: "Часто Задаваемые Вопросы",
    faq: [
      { q: "Как Luna хранит мои данные?", a: "Твои переписки и память привязаны к уникальному ключу устройства. Твои данные никогда не передаются и не продаются третьим лицам, и ты можешь полностью удалить их в любой момент." },
      { q: "Могу ли я использовать Luna и на телефоне, и на компьютере?", a: "Да. С помощью кода сопряжения, созданного в мобильном приложении, ты можешь привязать браузер к тому же аккаунту и синхронизировать память между устройствами." },
      { q: "В чём разница между Режимом Друга и Режимом LunaWorks?", a: "Режим Друга предлагает тёплое, личное, поддерживающее общение. Режим LunaWorks позволяет создавать PDF, документы Word, таблицы Excel, презентации PowerPoint, таблицы, графики и изображения прямо из этого же разговора. Переключаться между ними можно в любой момент." },
      { q: "Использование Luna бесплатно?", a: "Ты можешь начать пользоваться Luna бесплатно. Для более высокого лимита использования и расширенных функций доступны планы Luna Premium и Premium Plus." },
      { q: "Какие языки поддерживает Luna?", a: "Luna может естественно говорить на турецком, английском, испанском, немецком, русском и итальянском языках. Просто выбери язык в Настройках." },
    ],
    readyTitle: "Готов?",
    readySub: "Знакомство с Luna — всего в одном клике.",
    footerRights: "Все права защищены.",
  },
  it: {
    nav: ["Home", "Funzionalità", "Come Funziona", "Chi è Luna", "Sicurezza", "FAQ", "Contatti"],
    ctaStart: "Inizia Ora",
    badge: "LA TUA COMPAGNA IA",
    heroTitle: ["Non è solo un'IA", "che risponde alle domande."],
    heroLead: "una compagna IA personale che ti conosce, ti ricorda e cresce insieme a te nel tempo.",
    heroSub: "Più parli con lei, più impara — ricorda ciò che conta e diventa un'amica premurosa o un'assistente precisa, a seconda di ciò di cui hai bisogno.",
    ctaMeet: "Conosci Luna",
    ctaExplore: "Scopri le Funzionalità",
    onlineBadge: "Luna Online",
    onlineMsg: "Ciao! Come posso aiutarti oggi? 🌙",
    featuresTitle: "Cosa puoi fare con Luna?",
    featuresSub: "Cinque abilità fondamentali, ognuna oltre una comune assistente.",
    features: [
      { title: "Conversazione Naturale", desc: "Parla con te come un'amica vera, non come un'assistente robotica — fluida, naturale e senza mai perdere il contesto." },
      { title: "Memoria Intelligente", desc: "Ricorda i dettagli importanti, le preferenze e le date che le hai raccontato, così non devi mai ripeterti." },
      { title: "Pianificazione", desc: "Tiene traccia dei tuoi obiettivi, note e promemoria — aiutandoti a costruire e mantenere una routine quotidiana." },
      { title: "Supporto e Motivazione", desc: "In una giornata difficile, o quando hai bisogno di una spinta, Luna è presente come qualcuno che ti conosce davvero." },
      { title: "Privata e Sicura", desc: "La tua memoria e le tue conversazioni appartengono solo a te — protette da un'identità specifica del dispositivo, mai condivise con terzi." },
    ],
    howTitle: "Come Funziona Luna",
    howSub: "Tre semplici passi verso una compagna IA che ti conosce davvero.",
    how: [
      { title: "Parla", desc: "Inizia a chattare con Luna per testo o voce — un'amica premurosa in Modalità Amico, o una generatrice di documenti e immagini in Modalità LunaWorks." },
      { title: "Ricorda", desc: "Mentre parlate, Luna salva nella memoria i dettagli importanti, le preferenze e gli eventi — così non devi mai ripeterti." },
      { title: "Cresce Con Te", desc: "Man mano che la sua memoria cresce, ti capisce meglio — le sue risposte e il suo supporto diventano sempre più su misura per te." },
    ],
    aboutTitle: "Chi è Luna",
    aboutP1: ["Luna è una compagna IA personale sviluppata da XSF Technology. Non è un'assistente — punta a essere un'amica che ti conosce, ti ricorda e cresce insieme a te nel tempo. Puoi usarla in due modalità: calda e personale in ", "Modalità Amico", ", oppure generatrice di documenti e immagini in ", "Modalità LunaWorks", "."],
    aboutP2: "La maggior parte degli strumenti IA inizia ogni conversazione da zero. Luna funziona diversamente: con un sistema di memoria creato apposta per te, accumula nel tempo momenti importanti, preferenze e obiettivi — così, anche dopo giorni di silenzio, riprende esattamente da dove avevate lasciato, ricordandosi di te.",
    stats: [{ value: "24/7", label: "Sempre Presente" }, { value: "6 Lingue", label: "Supportate" }, { value: "100%", label: "Privata" }, { value: "2", label: "Personalità" }],
    securityTitle: "Sicurezza e Privacy",
    security: [
      "Le tue conversazioni e la tua memoria appartengono solo a te, protette da una chiave d'identità specifica del dispositivo.",
      "Per spostare la memoria tra telefono e web si usano codici di associazione monouso e a scadenza.",
      "Puoi eliminare completamente la tua memoria o la cronologia chat in qualsiasi momento.",
      "I tuoi dati non vengono mai condivisi o venduti a terzi.",
    ],
    faqTitle: "Domande Frequenti",
    faq: [
      { q: "Come memorizza Luna i miei dati?", a: "Le tue chat e la tua memoria sono legate a una chiave d'identità specifica del dispositivo. I tuoi dati non vengono mai condivisi o venduti a terzi e puoi eliminarli completamente in qualsiasi momento." },
      { q: "Posso usare Luna sia sul telefono che sul computer?", a: "Sì. Con il codice di associazione generato nell'app mobile, puoi collegare il tuo browser web allo stesso account e mantenere la memoria sincronizzata tra i due dispositivi." },
      { q: "Qual è la differenza tra Modalità Amico e Modalità LunaWorks?", a: "La Modalità Amico offre un'esperienza di conversazione calda, personale e di supporto. La Modalità LunaWorks ti permette di generare PDF, documenti Word, fogli Excel, presentazioni PowerPoint, tabelle, grafici e immagini dalla stessa conversazione. Puoi passare dall'una all'altra quando vuoi." },
      { q: "Usare Luna è gratuito?", a: "Puoi iniziare a usare Luna gratuitamente. Per un limite di utilizzo più alto e funzionalità avanzate sono disponibili i piani Luna Premium e Premium Plus." },
      { q: "Quali lingue supporta Luna?", a: "Luna può parlare naturalmente in turco, inglese, spagnolo, tedesco, russo e italiano. Basta scegliere la lingua nelle Impostazioni." },
    ],
    readyTitle: "Pronto?",
    readySub: "Conoscere Luna è a un solo clic di distanza.",
    footerRights: "Tutti i diritti riservati.",
  },
};

export function getLandingCopy(lang) {
  const base = RAW[lang] || RAW.en;
  return {
    ...base,
    features: withMeta(base.features, FEATURE_META),
    how: withMeta(base.how, HOW_META),
  };
}
